[platformio]
src_dir = .
default_envs = native_cpu, native_small, native_large, native_mixed, native_disabled, native_crc16_only, native_cfg_aliases

[env]
platform = native
test_framework = unity
test_build_src = yes
extra_scripts = pre:scripts/embedded_flags.py
build_src_filter = -<*> +<Crc.cpp> +<src/*.cpp>
build_flags = -I . -std=c++11 -Wall -Wextra -Werror

[env:native_cpu]
build_flags = ${env.build_flags} -DCRC_TABLE_SIZE=0

[env:native_small]
build_flags = ${env.build_flags} -DCRC_TABLE_SIZE=16

[env:native_large]
build_flags = ${env.build_flags} -DCRC_TABLE_SIZE=256

[env:native_mixed]
build_flags = ${env.build_flags} -DCRC8_TABLE_SIZE=0 -DCRC8H2F_TABLE_SIZE=16 -DCRC16_TABLE_SIZE=256 -DCRC32_TABLE_SIZE=16

[env:native_disabled]
build_flags = ${env.build_flags} -DCRC8_ENABLED=0 -DCRC8H2F_ENABLED=0 -DCRC16_ENABLED=0 -DCRC32_ENABLED=0

[env:native_crc16_only]
build_flags = ${env.build_flags} -DCRC8_ENABLED=0 -DCRC8H2F_ENABLED=0 -DCRC32_ENABLED=0

[env:native_cfg_aliases]
build_flags = ${env.build_flags} -DCFG_CRC8_ENABLE=0 -DCFG_CRC8H2F_ENABLE=0 -DCFG_CRC32_ENABLE=0
