[platformio]
default_envs = native, uno_cpu, uno_small, uno_large, esp32

[env]
lib_deps = symlink://../..
build_flags = -DCFG_CRC8_SMBUS_ENABLE=1 -DCFG_CRC8_ENABLE=0 -DCFG_CRC8H2F_ENABLE=0 -DCFG_CRC16_ENABLE=0 -DCFG_CRC32_ENABLE=0

[env:native]
platform = native
build_flags = ${env.build_flags} -std=c++11 -DCRC8_SMBUS_TABLE_SIZE=16

[env:uno_cpu]
platform = atmelavr
board = uno
framework = arduino
build_flags = ${env.build_flags} -DCRC8_SMBUS_TABLE_SIZE=0

[env:uno_small]
extends = env:uno_cpu
build_flags = ${env.build_flags} -DCRC8_SMBUS_TABLE_SIZE=16

[env:uno_large]
extends = env:uno_cpu
build_flags = ${env.build_flags} -DCRC8_SMBUS_TABLE_SIZE=256

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = ${env.build_flags} -DCRC8_SMBUS_TABLE_SIZE=256
