[platformio]
default_envs = native, uno, esp32

[env]
lib_deps = symlink://../..
build_flags =
    -DCRC_TABLE_SIZE=16
    -DCFG_CRC8_ENABLE=0
    -DCFG_CRC8H2F_ENABLE=0
    -DCFG_CRC32_ENABLE=0

[env:native]
platform = native
build_flags = ${env.build_flags} -std=c++11

[env:uno]
platform = atmelavr
board = uno
framework = arduino

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
